version: "3.8"

services:
  cloudflare:
    image: "cloudflare/cloudflared:latest"
    restart: "unless-stopped"
    command:
      - "tunnel"
      - "--no-autoupdate"
      - "run"
      - "--token"
      - "${CLOUDFLARE_TOKEN}"

networks:
  default: