name: dashdot

services:
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    container_name: "dashdot"
    privileged: true
    environment:
      DASHDOT_WIDGET_LIST: "os,cpu,storage,ram,network"
    expose:
      - "3001"
    ports:
      - "3001:3001"
    volumes:
      - "/:/mnt/host:ro"

