version: "3.8"

services:
  memos:
    image: "neosmemo/memos:stable"
    container_name: "memos"
    restart: "unless-stopped"
    volumes:
      - "memos:/var/opt/memos"
    expose:
      - "5230"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.memos.rule=Host(`memos.tqid.dev`)"
      - "traefik.http.routers.memos.entrypoints=web"

volumes:
  memos:

networks:
  default: