name: "prism"

services:
  app:
    image: photoprism/photoprism:latest
    restart: unless-stopped
    stop_grace_period: 15s
    depends_on:
      - db
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ## Server port mapping in the format "Host:Container". To use a different port, change the host port on
    ## the left-hand side and keep the container port, e.g. "80:2342" (for HTTP) or "443:2342 (for HTTPS):
    ports:
      - "2342:2342"
    ## Before you start the service, please check the following config options (and change them as needed):
    ## https://docs.photoprism.app/getting-started/config-options/
    environment:
      PHOTOPRISM_ADMIN_USER: "admin"
      PHOTOPRISM_ADMIN_PASSWORD: "${PRISM_ADMIN_PASSWORD}"
      PHOTOPRISM_AUTH_MODE: "password"
      PHOTOPRISM_DISABLE_TLS: "false"
      PHOTOPRISM_DEFAULT_TLS: "true"
      PHOTOPRISM_DEFAULT_LOCALE: "en"
      PHOTOPRISM_PLACES_LOCALE: "local"
      PHOTOPRISM_SITE_URL: "https://prism.tqid.dev/"  # server URL in the format "http(s)://domain.name(:port)/(path)"
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      PHOTOPRISM_SITE_DESCRIPTION: ""                # meta site description
      PHOTOPRISM_SITE_AUTHOR: ""                     # meta site author
      PHOTOPRISM_LOG_LEVEL: "info"                   # log level: trace, debug, info, warning, or error
      PHOTOPRISM_READONLY: "false"                   # do not modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false"              # disables updating storage permissions via chmod and chown on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # disables settings UI and API
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # disables face detection and recognition (requires TensorFlow)
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # disables image classification (requires TensorFlow)
      PHOTOPRISM_DISABLE_VECTORS: "false"            # disables vector graphics support
      PHOTOPRISM_DISABLE_RAW: "false"                # disables indexing and conversion of RAW images
      PHOTOPRISM_RAW_PRESETS: "false"                # enables applying user presets when converting RAW images (reduces performance)
      PHOTOPRISM_SIDECAR_YAML: "true"                # creates YAML sidecar files to back up picture metadata
      PHOTOPRISM_BACKUP_ALBUMS: "true"               # creates YAML files to back up album metadata
      PHOTOPRISM_BACKUP_DATABASE: "true"             # creates regular backups based on the configured schedule
      PHOTOPRISM_BACKUP_SCHEDULE: "daily"            # backup SCHEDULE in cron format (e.g. "0 12 * * *" for daily at noon) or at a random time (daily, weekly)
      PHOTOPRISM_INDEX_SCHEDULE: ""                  # indexing SCHEDULE in cron format (e.g. "@every 3h" for every 3 hours; "" to disable)
      PHOTOPRISM_AUTO_INDEX: 300                     # delay before automatically indexing files in SECONDS when uploading via WebDAV (-1 to disable)
      PHOTOPRISM_AUTO_IMPORT: -1                     # delay before automatically importing files in SECONDS when uploading via WebDAV (-1 to disable)
      PHOTOPRISM_DETECT_NSFW: "false"                # automatically flags photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # allows uploads that MAY be offensive (no effect without TensorFlow)
      PHOTOPRISM_UPLOAD_ALLOW: ""                    # restricts uploads to these file types (comma-separated list of EXTENSIONS; leave blank to allow all)
      PHOTOPRISM_UPLOAD_ARCHIVES: "true"             # allows upload of zip archives (will be extracted before import)
      PHOTOPRISM_UPLOAD_LIMIT: 5000                  # maximum size of uploaded files and uncompressed archive contents in MB
      PHOTOPRISM_ORIGINALS_LIMIT: 5000               # maximum size of original media files in MB (larger files are skipped)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
      # PHOTOPRISM_DATABASE_DRIVER: "sqlite"         # SQLite is an embedded database that does not require a separate database server
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # MariaDB 10.5.12+ (MySQL successor) offers significantly better performance compared to SQLite
      PHOTOPRISM_DATABASE_SERVER: "db:3306"     # MariaDB database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB database, see MARIADB_DATABASE in the mariadb service
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB database username, must be the same as MARIADB_USER
      PHOTOPRISM_DATABASE_PASSWORD: "${PRISM_MARIADB_PASSWORD}"       # MariaDB database password, must be the same as MARIADB_PASSWORD
      ## Run/install on first startup (https://docs.photoprism.app/getting-started/config-options/#docker-image):
      PHOTOPRISM_INIT: "https tensorflow"            # options: update https tensorflow tensorflow-gpu intel gpu davfs yt-dlp
      ## Computer Vision API (https://docs.photoprism.app/getting-started/config-options/#computer-vision):
      PHOTOPRISM_VISION_API: "false"                 # server: enables service API endpoints under /api/v1/vision (requires access token)
      PHOTOPRISM_VISION_URI: ""                      # client: service URI, e.g. http://hostname/api/v1/vision (leave blank to disable)
      PHOTOPRISM_VISION_KEY: ""                      # client: service access token (for authentication)
      ## Video Transcoding (https://docs.photoprism.app/getting-started/advanced/transcoding/):
      # PHOTOPRISM_FFMPEG_ENCODER: "software"        # H.264/AVC encoder (software, intel, nvidia, apple, raspberry, or vaapi)
      # PHOTOPRISM_FFMPEG_SIZE: "1920"               # video size limit in pixels (720-7680) (default: 3840)
      # PHOTOPRISM_FFMPEG_BITRATE: "64"              # video bitrate limit in Mbps (default: 60)
      ## Run as a non-root user after initialization (supported: 0, 33, 50-99, 500-600, and 900-1200):
      # PHOTOPRISM_UID: 1000
      # PHOTOPRISM_GID: 1000
      # PHOTOPRISM_UMASK: 0000
    ## Start as non-root user before initialization (supported: 0, 33, 50-99, 500-600, and 900-1200):
    # user: "1000:1000"
    ## Shared devices for video hardware transcoding (optional):
    devices:
     - "/dev/dri:/dev/dri"                         # Required Intel QSV or VAAPI hardware transcoding
    working_dir: "/photoprism" # do not change or remove
    ## Storage Folders: "~" is a shortcut for your home directory, "." for the current directory
    volumes:
      - "${PRISM_CACHE_FOLDER}:/photoprism/storage" # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)
      - "${PRISM_IMPORT_FOLDER}:/photoprism/import"                  # *Optional* base folder from which files can be imported to originals
      - "${PRISM_ORIGINALS_FOLDER}:/photoprism/originals"               # Original media files (DO NOT REMOVE)
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prism.rule=Host(`prism.tqid.dev`)"
      - "traefik.http.routers.prism.entrypoints=web"


  ## MariaDB Database Server (recommended)
  ## see https://docs.photoprism.app/getting-started/faq/#should-i-use-sqlite-mariadb-or-mysql
  db:
    image: mariadb:11
    restart: unless-stopped
    stop_grace_period: 15s
    security_opt: # see https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1136151239
      - seccomp:unconfined
      - apparmor:unconfined
    command: --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - "${PRISM_DB_LOCATION}:/var/lib/mysql" # DO NOT REMOVE
    ## See https://link.photoprism.app/mariadb-enviconment-variables:
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: "photoprism"
      MARIADB_USER: "photoprism"
      MARIADB_PASSWORD: "${PRISM_MARIADB_PASSWORD}"
      MARIADB_ROOT_PASSWORD: "${PRISM_MARIADB_ROOT_PASSWORD}"
      ## When specified, the container will connect to this host and replicate from it (for advanced users only):
      # MARIADB_MASTER_HOST: ""
      # MARIADB_REPLICATION_USER: ""
      # MARIADB_REPLICATION_PASSWORD: ""

#  ## Ollama Large-Language Model Runner (optional)
#  ## run "ollama pull [name]:[version]" to download a vision model
#  ## listed at <https://ollama.com/search?c=vision>, for example:
#  ## docker compose exec ollama ollama pull gemma3:latest
#  ollama:
#    image: ollama/ollama:latest
#    restart: unless-stopped
#    stop_grace_period: 15s
#    ## Only starts this service if the "all", "ollama", or "vision" profile is specified::
#    ## docker compose --profile ollama up -d
#    profiles: ["all", "ollama", "vision"]
#    ## Insecurely exposes the Ollama service on port 11434
#    ## without authentication (for private networks only):
#    # ports:
#    #  - "11434:11434"
#    environment:
#      ## Ollama Configuration Options:
#      OLLAMA_HOST: "0.0.0.0:11434"
#      OLLAMA_MODELS: "/root/.ollama"   # model storage path (see volumes section below)
#      OLLAMA_MAX_QUEUE: "100"          # maximum number of queued requests
#      OLLAMA_NUM_PARALLEL: "1"         # maximum number of parallel requests
#      OLLAMA_MAX_LOADED_MODELS: "1"    # maximum number of loaded models per GPU
#      OLLAMA_LOAD_TIMEOUT: "5m"        # maximum time for loading models (default "5m")
#      OLLAMA_KEEP_ALIVE: "5m"          # duration that models stay loaded in memory (default "5m")
#      OLLAMA_CONTEXT_LENGTH: "4096"    # maximum input context length
#      OLLAMA_MULTIUSER_CACHE: "false"  # optimize prompt caching for multi-user scenarios
#      OLLAMA_NOPRUNE: "false"          # disables pruning of model blobs at startup
#      OLLAMA_NOHISTORY: "true"         # disables readline history
#      OLLAMA_FLASH_ATTENTION: "false"  # enables the experimental flash attention feature
#      OLLAMA_KV_CACHE_TYPE: "f16"      # cache quantization (f16, q8_0, or q4_0)
#      OLLAMA_SCHED_SPREAD: "false"     # allows scheduling models across all GPUs.
#      OLLAMA_NEW_ENGINE: "true"        # enables the new Ollama engine
#      # OLLAMA_DEBUG: "true"             # shows additional debug information
#      # OLLAMA_INTEL_GPU: "true"         # enables experimental Intel GPU detection
#      ## NVIDIA GPU Hardware Acceleration (see https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html):
#      # NVIDIA_VISIBLE_DEVICES: "all"
#      # NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
#    volumes:
#      - "./ollama:/root/.ollama"
#    ## NVIDIA GPU Hardware Acceleration (see https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html):
#    # deploy:
#    #  resources:
#    #    reservations:
#    #      devices:
#    #        - driver: "nvidia"
#    #          capabilities: [ gpu ]
#    #          count: "all"

#  ## Open WebUI, a Web Interface for Ollama (optional)
#  ## see https://github.com/open-webui/open-webui
#  open-webui:
#    image: ghcr.io/open-webui/open-webui:main
#    restart: unless-stopped
#    stop_grace_period: 5s
#    ## Only starts this service if the "all", "ollama", "open-webui", or "vision" profile is specified::
#    ## docker compose --profile ollama up -d
#    profiles: [ "all", "ollama", "open-webui", "vision" ]
#    ## Exposes Open WebUI at http://localhost:8080 (use an HTTPS reverse proxy for remote access):
#    ports:
#      - "127.0.0.1:8080:8080"
#    environment:
#      WEBUI_URL: "http://localhost:8080"
#      # WEBUI_SECRET_KEY: ""
#      OLLAMA_BASE_URL: "http://ollama:11434"
#      ANONYMIZED_TELEMETRY: "false"   # disable Chroma telemetry
#      HF_HUB_DISABLE_TELEMETRY: "1"   # disable Hugging Face telemetry
#      # HUGGING_FACE_HUB_TOKEN: ""      # see https://huggingface.co/docs/hub/en/security-tokens
#    volumes:
#      - "./open-webui:/app/backend/data"
