version: "3.8"

services:
  traefik:
    image: "traefik:v3.2"
    restart: "unless-stopped"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.transport.respondingTimeouts.readTimeout=120s"
      - "--entrypoints.web.transport.respondingTimeouts.idleTimeout=120s"
      - "--entrypoints.web.transport.respondingTimeouts.writeTimeout=120s"
      - "--metrics.prometheus"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    expose:
      - "80"
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.tqid.dev`)"
      - "traefik.http.routers.dashboard.entrypoints=web"

networks:
  default:
