name: "Dash."

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/dashdot.yml
      - docker/dashdot.yml
    branches:
      - main

jobs:
  dashdot:
    runs-on: self-hosted
    env:
      CONFIG_FOLDER: "/mnt/unitek/config"
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f docker/dashdot.yml up --wait
