name: "Portainer"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/portainer.yml
      - docker/portainer.yml
    branches:
      - main

jobs:
  portainer:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f docker/portainer.yml up --wait
